### ISSUE TITLE
Null Object

### ISSUE THREAD

**Issue by Shocka12** [BoloVEVO/Kade-Engine#41]
i have little problem or im dumb.
I saw you updated the source and im downloaded and builded again. And i get the error.
![image](https://user-images.githubusercontent.com/122198793/231504227-ebb2d69b-92be-432b-975a-03a07ea1b850.png)

**Comment by Shocka12** [comment]
![image](https://user-images.githubusercontent.com/122198793/231505524-13858360-6e78-4dc6-ad47-a046f3a2ad29.png)
![image](https://user-images.githubusercontent.com/122198793/231505633-2a68144a-fd16-483d-8164-41359aa828e1.png)

**Comment by Shocka12** [comment]
![image](https://user-images.githubusercontent.com/122198793/231510902-5b14071d-c6fb-455b-9822-217705308a25.png)

**Comment by BoloVEVO** [comment]
do the same but with the export folder and check. This is very rare

**Comment by Shocka12** [comment]
![image](https://user-images.githubusercontent.com/122198793/231514029-6704fc1f-a705-44f9-a266-c3ccf2b548c8.png)

**Comment by BoloVEVO** [comment]
Go to Paths.hx and look for this and make sure you have `bitmap.unlock()` after  `bitmap = BitmapData.fromTexture(texture)` like this.
![image](https://user-images.githubusercontent.com/88955176/231520218-7be843d6-4a33-4bb8-a732-655eefeec094.png)


Fixed in [3cebdff](https://github.com/BoloVEVO/Kade-Engine/commit/3cebdff5980886067b6877032b3b433f5c304922)

**Comment by Shocka12** [comment]
Its... Worked! Thanks
